spring:
  application:
    name: Car Rental
  api:
    cors:  
    allowed-origins: ${ALLOWED_ORIGINS:'*'}
  jpa:
    open-in-view: false
    #properties:
    #  jakarta:
    #    persistence:
    #      schema-generation:
    #        scripts:
    #          action: create
    #          create-target: ./create.sql
    #          create-source: metadata   
  profiles:
    active: ${SPRING_PROFILE:dev}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
